wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.2
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706426231.720771
    t:
      1:
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 23
      4: 3.11.4
      5: 0.16.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
