wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709603121.429951
    t:
      1:
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
